@startuml "ClassDiagram"

skinparam ClassBorderColor MediumVioletRed
skinparam ObjectBorderColor MediumVioletRed
skinparam ArrowColor MediumBlue

skinparam class{
    BackgroundColor Gainsboro
}

skinparam object{
    BackgroundColor Gainsboro
}

skinparam note{
    BackgroundColor #ffdd8f
}

class Simulator as "Simulator"{
    -account
    -broker_API
    -charting
    -indicators_API
    -exporting_API
    -data_API
    -trigger_API
    -analyzer_API
    -strategy
    -start_date_unix
    -end_date_unix
    -augmented_start_date_unix
    -symbol
    -buy_list
    -sell_list
    -position_archive
    -reporting_on
    -charting_on
    -user_terminal_logging_on
    
    -error_check_strategy()
    -parse_strategy_timestamps()
    -parse_strategy_rules()
    -add_rsi()
    -add_upper_rsi()
    -add_lower_rsi()
    -add_sma()
    -add_buys_sells()
    -add_candle_colors()
    -create_position()
    -liquidate_position()
    -print_results()
    -datetime_nonce_string()
    -unix_to_string()
    -error_check_timestamps()
    +enable_logging()
    +enable_developer_logging()
    +enable_reporing()
    +enable_charting()
    +load_strategy()
    +run()
}

class UserAccount as "UserAccount"{
    -balance
    -initial_balance

    +get_balance()
    +deposit()
    +withdraw()
    +get_profit_loss()
}

class SimulationAnalyzer as "SimulationAnalyzer"{
    -positions
    -sum_cache
    -eff_cache
    -avg_pl_cache

    +effectiveness()
    +total_profit_loss()
    +avg_profit_loss()
}

class BrokerAPI as "BrokerAPI"{
    -API_KEY
    -SECRET_KEY
    -BASE_URL
    -BARS_URL
    -HEADERS
    -timeout
    -symbol

    -unix_to_utc_date()
    -unix_to_utc_time()
    -make_request()
    +get_daily_data()
    +get_hourly_data()
    +get_minute_data()
}

class ChartingAPI as "ChartingAPI"{
    -subplot_count
    -df
    -next_row
    -rsi_row
    
    +chart()
}

class ExportingAPI as "ExportingAPI"{
    -df
    -NONCE
    -workbook
    -data_worksheet
    -DATA_COLUMN_HEADER_ROW
    -DATA_COLUMN_HEADER_COL

    -add_titles()
    -write_df()
    -nonce()
    +load_data()
    +export()
}

class Indicators as "Indicators"{
    +candle_colors()
    +SMA()
    +RSI()
}

class Position as "Position"{
    -buy_price
    -sell_price
    -share_count

    +close_position()
    +profit_loss()
    +lifetime_profit_loss()
    +get_buy_price()
    +get_share_count()
    +get_sell_price()
}

class DataAPI as "DataAPI"{
    -df
    +CLOSE
    +OPEN
    +HIGH
    +LOW
    +VOLUME
    +COLOR

    +add_column()
    +get_data_length()
    +get_column_names()
    +get_data_point()
    +get_multiple_data_points()
    +get_column_data()
    +get_chopped_df()
}

class TriggerAPI as "TriggerAPI"{
    -strategy
    -data_object
    -position_object
    -current_day_index

    -clear_attributes()
    -handle_or_buy_tiggers()
    -handle_and_buy_triggers()
    -handle_or_sell_triggers()
    -handle_and_sell_triggers()
    -basic_triggers_check()
    -check_rsi_trigger()
    -check_sma_trigger()
    -check_volume_trigger()
    -check_candle_colors_trigger()
    -check_price_trigger()
    -check_stop_profit_trigger()
    -check_stop_loss_trigger()
    +check_buy_triggers()
    +check_sel_triggers()
}

Simulator -- UserAccount
Simulator -- BrokerAPI
Simulator -- ChartingAPI
Simulator -- Indicators
Simulator -- ExportingAPI
Simulator -- DataAPI
Simulator -- TriggerAPI
Simulator -- SimulationAnalyzer
Simulator -- Position

@enduml