name: Build StockBench with PyInstaller
on:
  push:
    branches:
      - release/*
jobs:
  Build:
    # using Windows to compile because .exe is target output
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install Dependencies
        run: pip install -r requirements.txt;

      - name: Build
        working-directory: ./src
        run: python build.py

      - name: Upload StockBench Executable Artifact
        uses: actions/upload-artifact@v7
        with:
          name: StockBench (Needs Version)
          # Only pick out the zip file that is in the dist folder
          path: src/dist/*.zip
